### ISSUE TITLE
SSL Support ?

### ISSUE THREAD

**Issue by ghost** [HarpyWar/myinstants-player#1]
It can be very good to have an SSL support! 

Thanks for this awesome and powerful version of myinstants for Sinusbot, keep it up!

Regards,
Dave

**Comment by HarpyWar** [comment]
Done.

**Comment by ghost** [comment]
I can't login and use it, here a screenshot: https://gyazo.com/586dc8306e96d17df24c54a5a40b4e7c

**Comment by HarpyWar** [comment]
@DavePS what IP address show ping to `api.cleanvoice.ru`? Did you try restart your browser?

**Comment by ghost** [comment]
Réponse de 5.9.10.202 : octets=32 temps=23 ms TTL=110

Restarted the browser too but not working, here a screen hope it help https://i.gyazo.com/8670c6781c38ccb4a7451c84a6214f69.png

**Comment by HarpyWar** [comment]
There were changes made to support SSL, and this address should response to 5.9.45.235
Try `ipconfig /fushdns` to clear local DNS cache. If it doesn't help then change your DNS servers to Google. Or just wait for 24 hours while it updated.

**Comment by ghost** [comment]
Now working, I flushed my dns and all's good for pages content. 

Here is my ping now : 

Réponse de 5.9.45.235 : octets=32 temps=77 ms TTL=110

Btw when I click on a button the bot don't send music, I tryed with another browser but not working too.

**Comment by HarpyWar** [comment]
I forgot that SinusBot doesn't support SSL for external urls by default. Now it should works.

**Comment by ghost** [comment]
Good job mate.
